import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import Layout from '@/components/Layout';
import Heading from '@/components/Heading';
import Paragraph from '@/components/Paragraph';
import { AllPosts } from '@/lib/hygraph/queries';
import { GetStaticProps } from 'next';
import { ListItem,List,Card,CardMedia,CardContent,CardActions} from '@mui/material';


// const inter = Inter({ subsets: ['latin'] })
interface BlogProps {
  ssd: any[]; // Replace 'any' with the actual type of your blog posts
}


const Blog:React.FC<BlogProps>=({ssd=[]}) => {
  console.log({ssd})
  return (
    
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
      <Heading variant="h2" component="h2" >Blog List</Heading>
        <List component={"ol"} sx={{ listStyle: "none" }}>
          {ssd.map(({ id, title, slug, heroImage}) => {

            const firstImageUrl:string = heroImage[0].url
            return(
            <ListItem key={id}>
              <Card component={"article"} sx={{width:'100%'}}>
                <CardMedia>
                  <Image alt={title} src={firstImageUrl} width="235" height="200" />
                </CardMedia>
                <CardContent>
                  <Heading variant="h3" component="h2">{title}</Heading>
                </CardContent>
                <CardActions>
                  <Link href={`/blog/${slug}`}>Read more...</Link>
                </CardActions>
              </Card>
            </ListItem>
          )})}
        </List>
        </Layout>
      
    </>
  )
}

export const getStaticProps: GetStaticProps<BlogProps> = async () => {
  const allPosts = await fetch(`${process.env.HYGRAPH_ENDPOINT}`, {
    method: "POST",
    headers: {
      "Content-Type": `application/json; charset="UTF-8`,
      Authorization: `Bearer ${process.env.HYGRAPH_TOKEN}`,
    },
    body: JSON.stringify({
      query: AllPosts,
    }),
  })
    .then((res) => res.json())
    .catch((err) => console.log(err));
  console.log(allPosts);
  const posts = allPosts.data.blogs;
  console.log(posts);
  return {
    props: {
      ssd: posts,
    },
  };
};
export default Blog