import Head from 'next/head'
import Image from 'next/image'
import Layout from '@/components/Layout';
import Heading from '@/components/Heading';
import Paragraph from '@/components/Paragraph';
import { AllPosts } from '@/lib/hygraph/queries';
import { GetStaticProps } from 'next';

// const inter = Inter({ subsets: ['latin'] })
interface BlogProps {
  ssd: any[]; // Replace 'any' with the actual type of your blog posts
}

const { HYGRAPH_ENDPOINT, HYGRAPH_TOKEN } = process.env;
const Blog:React.FC<BlogProps>=({ssd=[]}) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
      <Heading variant="h2" component="h2" >Blog List</Heading>
        <Paragraph>
          Use the form below to get in touch
        </Paragraph>
       
        
        </Layout>
      
    </>
  )
}

export const getStaticProps: GetStaticProps<BlogProps> = async () => {
  const allPosts = await fetch(`${HYGRAPH_ENDPOINT}`, {
    method: "POST",
    headers: {
      "Content-Type": `application/json; charset="UTF-8`,
      Authorization: `Bearer ${HYGRAPH_TOKEN}`,
    },
    body: JSON.stringify({
      query: AllPosts,
    }),
  })
    .then((res) => res.json())
    .catch((err) => console.log(err));
  console.log(allPosts);
  const posts = allPosts.data.blogs;
  console.log(posts);
  return {
    props: {
      ssd: posts,
    },
  };
};
export default Blog