import Head from 'next/head'
// import Image from 'next/image'
import { Inter } from 'next/font/google'
import { Button, EditIcon } from '@/components/mui/index';

import Layout from '@/components/Layout';
import Heading from '@/components/Heading';
import Paragraph from '@/components/Paragraph';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Heading variant="h2" component="h2" >Home Page</Heading>
        <Paragraph>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec venenatis sagittis leo, at sollicitudin nibh blandit in. Donec sit amet diam turpis. Aenean mattis sagittis augue vel placerat. Donec posuere elit sem, non varius tellus vestibulum in. Fusce auctor diam est, in eleifend quam commodo a. Proin felis libero, posuere a nisl sed, gravida condimentum turpis. Suspendisse fringilla, lacus mollis euismod eleifend, nisi neque pellentesque eros, eget congue velit tortor non est.

        </Paragraph>
        <Button variant="contained">
          <EditIcon />
          Button
        </Button>

      </Layout>

    </>
  )
}
